name: Deploy New Project

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup SSH Connection
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

    - name: Deploy to Server
      run: |
        BRANCH=${GITHUB_REF##*/}  # Ambil nama branch dari push event

        ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << EOF
          cd ~/NewDockerProject  # Sesuaikan dengan folder proyek Anda

          echo "Using branch: ${BRANCH}"

          echo "Resetting local changes..."
          git reset --hard origin/${BRANCH}
          git clean -fd

          echo "Pulling latest changes..."
          git pull origin ${BRANCH}

          echo "Restarting Docker containers..."
          docker compose down
          docker compose up --build -d

          echo "Cleaning up old images..."
          docker system prune -af

          echo "Deployment completed!"
        EOF

# name: Build and Push Docker image to Docker Hub

# on:
#   push:
#     branches:
#       - master  # Workflow ini akan berjalan setiap ada perubahan di branch 'main'

# jobs:
#   build:
#     runs-on: ubuntu-latest  # Workflow ini akan dijalankan di Ubuntu terbaru

#     steps:
#       # Step 1: Checkout repository
#       - name: Checkout repository
#         uses: actions/checkout@v2

#       # Step 2: Login ke Docker Hub
#       - name: Log in to Docker Hub
#         uses: docker/login-action@v2
#         with:
#           username: ${{ secrets.DOCKER_USERNAME }}
#           password: ${{ secrets.DOCKER_PASSWORD }}

#       # Step 3: Build Docker image
#       - name: Build Docker image
#         run: |
#           docker build -t ikbalyuliyanto7/quilvian-postgre-api:latest .

#       # Step 4: Push Docker image to Docker Hub
#       - name: Push Docker image
#         run: |
#           docker push ikbalyuliyanto7/quilvian-postgre-api:latest
